"""widget_user_permissions

Revision ID: fe0fda81085d
Revises: f4ce8a36362a
Create Date: 2026-03-31 20:40:45.045955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0fda81085d'
down_revision = 'f4ce8a36362a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_widget_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['family_widget_id'], ['family_widgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_widget_id', 'user_id', name='uq_widget_user')
    )
    op.drop_table('widget_role_permissions')
    with op.batch_alter_table('family_widgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grid_col', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grid_row', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grid_pos_x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grid_pos_y', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_system_admin')

    with op.batch_alter_table('family_widgets', schema=None) as batch_op:
        batch_op.drop_column('grid_pos_y')
        batch_op.drop_column('grid_pos_x')
        batch_op.drop_column('grid_row')
        batch_op.drop_column('grid_col')

    op.create_table('widget_role_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('family_widget_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('can_view', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_edit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['family_widget_id'], ['family_widgets.id'], name=op.f('widget_role_permissions_family_widget_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('widget_role_permissions_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('widget_role_permissions_pkey')),
    sa.UniqueConstraint('family_widget_id', 'role_id', name=op.f('uq_widget_role'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('widget_user_permissions')
    # ### end Alembic commands ###
